import type { Agent } from '@/types/prompt'

export const PREDEFINED_AGENTS: Agent[] = [
  {
    id: 'agent_dev_senior',
    name: 'Dev Senior · Seguridad',
    description: 'Auditoría de código, vulnerabilidades y arquitectura',
    icon: '🔍',
    role: 'Eres un senior full-stack developer especialista en React, Supabase y seguridad de aplicaciones web',
    systemPrompt: '',
    model: 'claude',
    tools: [],
    techniques: ['cot', 'xml', 'neg'],
    skillIds: ['skill_nexus_context', 'skill_no_hallucination', 'skill_scope_min'],
    outputFormat: 'informe estructurado con secciones y subsecciones numeradas',
    autonomyLevel: 'execute_declare',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
    isCustom: false,
  },
  {
    id: 'agent_nis2',
    name: 'Consultor NIS2',
    description: 'Cumplimiento normativo y auditoría de seguridad para PYME',
    icon: '🛡️',
    role: 'Eres un consultor de ciberseguridad especialista en NIS2, auditoría de sistemas y cumplimiento normativo para PYME',
    systemPrompt: '',
    model: 'claude',
    tools: [],
    techniques: ['cot', 'xml', 'neg', 'crit'],
    skillIds: ['skill_nexus_context', 'skill_no_hallucination'],
    outputFormat: 'informe estructurado con secciones y subsecciones numeradas',
    autonomyLevel: 'execute_declare',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
    isCustom: false,
  },
  {
    id: 'agent_copywriter',
    name: 'Copywriter B2B',
    description: 'Emails, propuestas comerciales y posts LinkedIn para PYME',
    icon: '✉️',
    role: 'Eres un copywriter B2B especialista en emails de captación y contenido comercial para PYME',
    systemPrompt: '',
    model: 'claude',
    tools: [],
    techniques: ['neg', 'pre'],
    skillIds: ['skill_nexus_context', 'skill_spanish_output'],
    outputFormat: 'respuesta directa y concisa sin introducción ni relleno',
    autonomyLevel: 'execute_declare',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
    isCustom: false,
  },
  {
    id: 'agent_architect_ia',
    name: 'Arquitecto IA',
    description: 'Diseño de system prompts y agentes de producción',
    icon: '🤖',
    role: 'Eres un arquitecto de software especialista en sistemas de IA, diseño de system prompts y agentes de producción',
    systemPrompt: '',
    model: 'claude',
    tools: [],
    techniques: ['sc', 'neg', 'ej', 'pre'],
    skillIds: ['skill_nexus_context', 'skill_plan_first', 'skill_no_hallucination'],
    outputFormat: 'código listo para copiar, sin explicaciones adicionales',
    autonomyLevel: 'execute_declare',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
    isCustom: false,
  },
]
