import type { Skill } from '@/types/prompt'

export const PREDEFINED_SKILLS: Skill[] = [
  // ── Behavior ──────────────────────────────────────────────────────────────
  {
    id: 'skill_cot',
    name: 'Razonamiento paso a paso',
    description: 'Fuerza a la IA a razonar antes de responder',
    icon: '🧠',
    category: 'behavior',
    content: 'Antes de dar la respuesta final, razona paso a paso en un bloque <razonamiento>. Solo después entrega el resultado.',
    insertTarget: 'tarea',
    isPredefined: true,
    isExportable: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'skill_plan_first',
    name: 'Plan antes de ejecutar',
    description: 'Obliga a crear un plan de ejecución antes del código',
    icon: '📋',
    category: 'behavior',
    content: 'Antes de implementar, genera un bloque <plan_ejecucion> con los pasos ordenados, archivos afectados y posibles riesgos. Solo procede con el código tras el plan.',
    insertTarget: 'tarea',
    isPredefined: true,
    isExportable: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'skill_scope_min',
    name: 'Scope mínimo',
    description: 'No tocar nada fuera del scope exacto solicitado',
    icon: '🎯',
    category: 'behavior',
    content: 'Modifica únicamente lo que se solicita. No refactorices, no reorganices, no mejores nada que no esté en el scope. Si ves algo mejorable fuera del scope, menciónalo al final sin implementarlo.',
    insertTarget: 'restriccion',
    isPredefined: true,
    isExportable: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  // ── Security ──────────────────────────────────────────────────────────────
  {
    id: 'skill_no_hallucination',
    name: 'Anti-alucinación',
    description: 'Distingue entre hechos confirmados y suposiciones',
    icon: '🛡️',
    category: 'security',
    content: 'Distingue siempre entre hechos confirmados y suposiciones. Si no tienes seguridad sobre algo, indícalo con [SUPUESTO]. No inventes APIs, funciones, archivos ni comportamientos que no hayas visto en el material adjunto.',
    insertTarget: 'restriccion',
    isPredefined: true,
    isExportable: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'skill_ask_missing',
    name: 'Pide lo que falta',
    description: 'Si falta información crítica, pídela antes de continuar',
    icon: '❓',
    category: 'security',
    content: 'Si para completar la tarea necesitas ver un archivo, dato o contexto que no se ha proporcionado, pídelo explícitamente antes de asumir su contenido. Lista exactamente qué necesitas y por qué.',
    insertTarget: 'autonomia',
    isPredefined: true,
    isExportable: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  // ── Format ────────────────────────────────────────────────────────────────
  {
    id: 'skill_code_only',
    name: 'Solo código, sin explicaciones',
    description: 'Responde con código listo para copiar, sin texto adicional',
    icon: '💻',
    category: 'format',
    content: 'Responde únicamente con el código listo para aplicar. Sin introducción, sin explicaciones, sin conclusión. Si hay varios archivos, sepáralos con un comentario // filepath: ruta/al/archivo.',
    insertTarget: 'restriccion',
    isPredefined: true,
    isExportable: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'skill_xml_tags',
    name: 'Estructurar con XML tags',
    description: 'Usa etiquetas XML para separar secciones del output',
    icon: '🏷️',
    category: 'format',
    content: 'Estructura tu respuesta usando etiquetas XML para cada sección. Ejemplo: <analisis>, <solucion>, <codigo>, <riesgos>, <supuestos>. Esto facilita parsear tu respuesta.',
    insertTarget: 'tarea',
    isPredefined: true,
    isExportable: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  // ── Context ───────────────────────────────────────────────────────────────
  {
    id: 'skill_nexus_context',
    name: 'Contexto Nexus',
    description: 'Inyecta el contexto de la empresa en el prompt',
    icon: '🏢',
    category: 'context',
    content: 'Contexto de empresa: Nexus convierte ideas en sistemas de IA reutilizables con prompts, skills, agentes y workflows. Stack técnico: Next.js, React, TypeScript, Supabase, Tailwind CSS. El código debe ser de producción, tipado estricto y sin deuda técnica.',
    insertTarget: 'system',
    isPredefined: true,
    isExportable: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'skill_spanish_output',
    name: 'Responder en español',
    description: 'Fuerza las respuestas siempre en español neutro',
    icon: '🇪🇸',
    category: 'context',
    content: 'Responde siempre en español neutro (no Latinoamérica). Usa terminología técnica en inglés cuando sea estándar del sector (component, hook, deploy, etc.) pero el resto del texto en español.',
    insertTarget: 'restriccion',
    isPredefined: true,
    isExportable: true,
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
]

export const SKILL_CATEGORY_LABELS: Record<string, string> = {
  behavior: 'Comportamiento',
  format: 'Formato',
  context: 'Contexto',
  security: 'Seguridad',
  workflow: 'Workflow',
  custom: 'Custom',
}

export const SKILL_CATEGORY_COLORS: Record<string, string> = {
  behavior: 'text-accent-purple border-accent-purple/30 bg-accent-purple/10',
  format:   'text-accent-blue border-accent-blue/30 bg-accent-blue/10',
  context:  'text-accent border-accent/30 bg-accent/10',
  security: 'text-red-400 border-red-400/30 bg-red-400/10',
  workflow: 'text-orange-400 border-orange-400/30 bg-orange-400/10',
  custom:   'text-muted border-border bg-surface2',
}
