import { PromptTemplate } from '@/types/prompt';

export const TEMPLATES: Record<string, PromptTemplate> = {

  // ─── DESARROLLO WEB ──────────────────────────────────────────────────────────

  audit: {
    rol: 'Eres un senior developer y experto en seguridad de aplicaciones web',
    tarea: 'Analiza el código adjunto. Detecta: vulnerabilidades de seguridad (XSS, SQLi, auth débil), errores lógicos, código duplicado o muerto, y malas prácticas. Clasifica cada hallazgo por severidad: crítica, alta, media, baja.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: '',
    outputType: 'informe estructurado con secciones y subsecciones numeradas',
    ext: 'respuesta detallada y completa, sin omitir ningún punto relevante',
    tono: 'técnico y preciso, asumiendo que el lector tiene conocimiento del área',
    cot: true,
    sc: false,
    xml: true,
    neg: true,
    ej: false,
    pre: false,
    matType: 'codigo',
    matFile: '',
    quickSummary: 'Detecta XSS, SQLi, auth débil y malas prácticas por severidad',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Código a auditar', placeholder: 'Pega aquí el código completo que quieres auditar...' },
      { id: 'matFile', status: 'required', label: 'Nombre del archivo', placeholder: 'Hero.tsx, api/route.ts, utils.ts...' },
      { id: 'stack', status: 'required', label: 'Stack', placeholder: 'React + Supabase, Next.js, FastAPI + PostgreSQL...' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  fix: {
    rol: 'Eres un senior developer especialista en debugging y refactorización de código',
    tarea: '1. Identifica la causa raíz exacta del bug descrito. 2. Propón la solución mínima necesaria — sin reescribir lo que funciona. 3. Muestra únicamente el bloque de código corregido listo para aplicar.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'no cambies nada fuera del scope exacto del bug',
    outputType: 'código corregido listo para copiar, sin explicaciones adicionales',
    ext: 'respuesta concisa, máximo 150 palabras, sin relleno',
    tono: 'técnico y preciso, asumiendo que el lector tiene conocimiento del área',
    cot: true,
    sc: false,
    xml: false,
    neg: true,
    ej: false,
    pre: false,
    matType: 'error',
    matFile: '',
    quickSummary: 'Causa raíz + código corregido mínimo, sin tocar lo que funciona',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Describe el bug o pega el error', placeholder: 'Error en consola, stack trace, descripción del comportamiento incorrecto...' },
      { id: 'stack', status: 'required', label: 'Stack', placeholder: 'React, Node.js, Python, etc.' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricción' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  componente: {
    rol: 'Eres un senior frontend developer especialista en componentes UI, accesibilidad web y sistemas de diseño',
    tarea: 'Crea el componente descrito. Requisitos: 1) props bien tipadas con valores por defecto, 2) accesible (aria labels donde aplique), 3) manejo de estados de carga y error, 4) exportación por defecto. Incluye un ejemplo de uso al final en comentario.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'no uses librerías externas salvo las ya indicadas en el stack',
    outputType: 'código listo para copiar, sin explicaciones adicionales',
    ext: 'respuesta detallada y completa, sin omitir ningún punto relevante',
    tono: 'técnico y preciso, asumiendo que el lector tiene conocimiento del área',
    cot: false,
    sc: true,
    xml: false,
    neg: true,
    ej: false,
    pre: true,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'Componente tipado con accesibilidad, estados y ejemplo de uso',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Describe el componente', placeholder: 'Nombre, props, comportamiento, variantes, estado que maneja...' },
      { id: 'stack', status: 'required', label: 'Stack / framework', placeholder: 'React + Tailwind, Vue, Svelte, Angular...' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricción' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  refactor: {
    rol: 'Eres un senior developer especialista en clean code, patrones de diseño y rendimiento',
    tarea: 'Refactoriza el código adjunto. Objetivos por orden de prioridad: 1) eliminar duplicados y código muerto, 2) mejorar legibilidad y nombres, 3) aplicar principios SOLID donde aplique, 4) optimizar rendimiento si hay mejoras evidentes. No cambies la funcionalidad.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'mantén la API pública del módulo intacta — no rompas contratos existentes',
    outputType: 'código refactorizado listo para copiar, con comentarios inline solo donde el cambio no sea obvio',
    ext: 'respuesta detallada y completa, sin omitir ningún punto relevante',
    tono: 'técnico y preciso, asumiendo que el lector tiene conocimiento del área',
    cot: false,
    sc: true,
    xml: false,
    neg: true,
    ej: false,
    pre: false,
    matType: 'codigo',
    matFile: '',
    quickSummary: 'Clean code sin cambiar funcionalidad ni API pública del módulo',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Código a refactorizar', placeholder: 'Pega aquí el código que quieres limpiar y mejorar...' },
      { id: 'stack', status: 'required', label: 'Stack', placeholder: 'TypeScript, Python, Java, etc.' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricción' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  conversion: {
    rol: 'Eres un arquitecto frontend especialista en migración de sistemas legacy a arquitecturas modernas',
    tarea: 'Convierte el código adjunto a la arquitectura objetivo. Pasos: 1) descomponer en componentes atómicos y funcionales, 2) migrar estilos a la solución indicada, 3) implementar hooks o equivalentes para la interactividad, 4) asegurar accesibilidad y rendimiento.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'no hagas un simple copiar y pegar. Refactoriza hacia la arquitectura objetivo con tipado y buenas prácticas.',
    outputType: 'código refactorizado listo para copiar',
    ext: 'respuesta detallada y completa',
    tono: 'técnico y preciso, asumiendo que el lector tiene conocimiento del área',
    cot: true,
    sc: true,
    xml: true,
    neg: true,
    ej: false,
    pre: false,
    matType: 'codigo',
    matFile: '',
    criterios: 'Arquitectura limpia, separación de lógica y UI, tipado correcto.',
    quickSummary: 'Legacy → arquitectura moderna con componentes y buenas prácticas',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Código legacy a convertir', placeholder: 'Pega aquí el código HTML, JS, CSS o framework anterior que quieres migrar...' },
      { id: 'stack', status: 'required', label: 'Stack objetivo', placeholder: 'Next.js + TypeScript, React + Vite, Vue 3, etc.' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricción' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  app_existente: {
    rol: 'Eres un senior developer especialista en mantener y evolucionar aplicaciones en producción sin romper lo que ya funciona',
    tarea: 'La app ya está creada y en uso. Realiza el cambio, mejora o fix solicitado. Reglas: 1) no toques nada fuera del scope exacto del cambio, 2) si necesitas ver un archivo existente para no inventar su contenido, pídelo, 3) entrega solo el bloque de código modificado listo para aplicar, 4) declara al final cualquier suposición que hayas hecho.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'no reestructures la arquitectura ni cambies convenciones del proyecto sin que se te pida. Scope mínimo, impacto máximo.',
    outputType: 'código listo para copiar, sin explicaciones adicionales',
    ext: 'respuesta concisa, máximo 150 palabras, sin relleno',
    tono: 'técnico y preciso, asumiendo que el lector tiene conocimiento del área',
    promptPhase: 'fase 0: app ya creada — mejora, fix o auditoria',
    cot: true,
    sc: false,
    xml: false,
    neg: true,
    ej: false,
    pre: false,
    matType: 'codigo',
    matFile: '',
    quickSummary: 'Fix/mejora puntual: scope mínimo, sin tocar lo que ya funciona',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Cambio a realizar o código afectado', placeholder: 'Describe el cambio, mejora o fix. Pega el código relevante si aplica...' },
      { id: 'stack', status: 'required', label: 'Stack', placeholder: 'Next.js + TypeScript, Django, etc.' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricciones' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  // ─── BACKEND Y DATOS ─────────────────────────────────────────────────────────

  python: {
    rol: 'Eres un senior Python developer especialista en código limpio, rendimiento y buenas prácticas (PEP 8, type hints, manejo de errores)',
    tarea: 'Implementa lo descrito en Python. Requisitos: 1) type hints en todas las funciones, 2) docstrings concisos donde el comportamiento no sea obvio, 3) manejo de errores explícito con excepciones tipadas, 4) código listo para producción.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'no uses librerías externas salvo las indicadas en el stack. Si necesitas una, justifícalo antes de usarla.',
    outputType: 'código Python listo para copiar',
    ext: 'respuesta detallada y completa',
    tono: 'técnico y preciso',
    cot: false,
    sc: true,
    xml: false,
    neg: true,
    ej: false,
    pre: true,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'Python tipado, PEP 8, type hints y manejo de errores explícito',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Qué necesitas implementar', placeholder: 'Función, clase, script, endpoint de API, tarea de procesamiento...' },
      { id: 'stack', status: 'required', label: 'Librerías / framework', placeholder: 'FastAPI, Django, pydantic, SQLAlchemy, pandas...' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricción' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  api_rest: {
    rol: 'Eres un arquitecto de APIs con experiencia en diseño de contratos REST, autenticación, versionado y documentación OpenAPI',
    tarea: 'Diseña e implementa la API descrita. Entrega: 1) endpoints con método, ruta y descripción, 2) esquemas de request/response, 3) códigos de estado y manejo de errores, 4) ejemplo de llamada con curl o fetch.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'sigue los principios REST: recursos en sustantivos, uso correcto de verbos HTTP, respuestas consistentes en formato y errores',
    outputType: 'código listo para copiar con documentación inline',
    ext: 'respuesta detallada y completa',
    tono: 'técnico y preciso',
    cot: true,
    sc: false,
    xml: true,
    neg: true,
    ej: true,
    pre: false,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'API REST: endpoints, esquemas, errores y ejemplos curl/fetch',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Qué debe hacer la API', placeholder: 'Recursos, operaciones CRUD, autenticación, integraciones, casos de uso...' },
      { id: 'stack', status: 'required', label: 'Stack / framework', placeholder: 'FastAPI, Express, Django REST, Next.js API routes, Rails...' },
      { id: 'restriccion', status: 'prefilled', label: 'Principios REST' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  sql_bd: {
    rol: 'Eres un DBA y backend developer especialista en modelado de datos, SQL avanzado y optimización de consultas',
    tarea: 'Resuelve la tarea de base de datos descrita. Entrega: 1) SQL listo para ejecutar, 2) explicación de decisiones de diseño importantes, 3) índices recomendados si aplica, 4) consideraciones de rendimiento y escalabilidad.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'no inventes nombres de tablas o columnas que no estén en el material. Si falta información, pídela antes de asumir.',
    outputType: 'SQL listo para ejecutar con comentarios donde no sea obvio',
    ext: 'respuesta detallada y completa',
    tono: 'técnico y preciso',
    cot: true,
    sc: false,
    xml: false,
    neg: true,
    ej: false,
    pre: true,
    matType: 'contexto',
    matFile: '',
    evidenceMode: true,
    quickSummary: 'SQL ejecutable: esquema, consultas, índices y decisiones de diseño',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Qué necesitas resolver', placeholder: 'Esquema actual, consulta que falla, datos de ejemplo, requisito de negocio...' },
      { id: 'stack', status: 'required', label: 'Motor de base de datos', placeholder: 'PostgreSQL, MySQL, SQLite, Supabase, MongoDB...' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricción de datos' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  data_science: {
    rol: 'Eres un data scientist especialista en Python, análisis estadístico, visualización y modelos predictivos',
    tarea: 'Analiza los datos descritos o adjuntos. Entrega: 1) exploración inicial (tipos, nulos, distribuciones), 2) transformaciones o limpieza necesaria, 3) análisis o modelo solicitado, 4) visualización o tabla de resultados con conclusión accionable.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'separa hechos observados en los datos de interpretaciones tuyas. Indica explícitamente si hay datos insuficientes para una conclusión sólida.',
    outputType: 'código Python ejecutable con comentarios en los pasos clave',
    ext: 'respuesta detallada y completa',
    tono: 'técnico y preciso, con conclusiones en lenguaje claro',
    cot: true,
    sc: false,
    xml: false,
    neg: true,
    ej: false,
    pre: false,
    evidenceMode: true,
    matType: 'datos',
    matFile: '',
    quickSummary: 'Análisis de datos: exploración, modelo y conclusión accionable',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Datos o descripción del análisis', placeholder: 'Muestra de datos, columnas disponibles, pregunta de negocio a responder...' },
      { id: 'stack', status: 'required', label: 'Librerías Python', placeholder: 'pandas, numpy, matplotlib, scikit-learn, plotly, seaborn...' },
      { id: 'restriccion', status: 'prefilled', label: 'Política de evidencia' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  // ─── INFRAESTRUCTURA Y CALIDAD ───────────────────────────────────────────────

  testing: {
    rol: 'Eres un senior QA engineer y developer especialista en testing: unit tests, integración, e2e y contract testing',
    tarea: 'Escribe los tests para el código adjunto. Requisitos: 1) cubrir el happy path, 2) al menos 2 edge cases por función, 3) casos de error con inputs inválidos, 4) tests legibles: el nombre describe exactamente qué comportamiento valida.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'no testees implementación interna — testea comportamiento observable. No mockees lo que puedes usar directamente.',
    outputType: 'código de tests listo para copiar',
    ext: 'respuesta detallada y completa',
    tono: 'técnico y preciso',
    cot: false,
    sc: true,
    xml: false,
    neg: true,
    ej: false,
    pre: true,
    matType: 'codigo',
    matFile: '',
    quickSummary: 'Tests: happy path + edge cases + errores, sin mockear lo innecesario',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Código a testear', placeholder: 'Pega el código que quieres cubrir con tests...' },
      { id: 'stack', status: 'required', label: 'Framework de testing', placeholder: 'Jest, Vitest, pytest, Playwright, Cypress, RSpec...' },
      { id: 'restriccion', status: 'prefilled', label: 'Política de mocks' },
      { id: 'criterios', status: 'advanced', label: 'Criterios de cobertura' },
    ],
  },

  devops: {
    rol: 'Eres un DevOps engineer y SRE especialista en infraestructura como código, CI/CD, contenedores y observabilidad',
    tarea: 'Implementa la configuración de infraestructura o pipeline descrita. Requisitos: 1) lista para producción, 2) secretos nunca en el código — solo en variables de entorno, 3) falla rápido con mensajes de error claros, 4) documenta todas las variables de entorno necesarias.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'no hardcodees credenciales, IPs ni rutas absolutas del sistema. Todo configurable por variables de entorno.',
    outputType: 'configuración lista para copiar con variables de entorno documentadas',
    ext: 'respuesta detallada y completa',
    tono: 'técnico y preciso',
    cot: true,
    sc: false,
    xml: false,
    neg: true,
    ej: false,
    pre: false,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'CI/CD o infra lista para producción, sin credenciales hardcodeadas',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Qué necesitas configurar', placeholder: 'Pipeline CI/CD, Dockerfile, docker-compose, despliegue, monitorización...' },
      { id: 'stack', status: 'required', label: 'Plataforma / herramientas', placeholder: 'GitHub Actions, Docker, Vercel, AWS, Railway, Kubernetes...' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricción de seguridad' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  automatizacion: {
    rol: 'Eres un senior developer y SRE especialista en automatización, scripting y procesos batch robustos',
    tarea: 'Implementa el script o automatización descrita. Requisitos: 1) manejo de errores con mensajes claros y código de salida correcto, 2) logs de progreso para procesos largos, 3) idempotente cuando sea posible — re-ejecutable sin efectos secundarios, 4) variables configurables documentadas al inicio.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'no hardcodees rutas, credenciales ni parámetros — todo como variables configurables al inicio del script.',
    outputType: 'script completo listo para ejecutar',
    ext: 'respuesta detallada con comentarios en los bloques no obvios',
    tono: 'técnico y preciso',
    cot: false,
    sc: true,
    xml: false,
    neg: true,
    ej: false,
    pre: true,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'Script idempotente con errores, logs y variables configurables al inicio',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Qué necesitas automatizar', placeholder: 'Proceso, tarea repetitiva, integración entre sistemas, procesamiento batch...' },
      { id: 'stack', status: 'required', label: 'Lenguaje / entorno', placeholder: 'Python, Bash, PowerShell, Node.js, GitHub Actions...' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricción de configuración' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  // ─── MOBILE ──────────────────────────────────────────────────────────────────

  mobile: {
    rol: 'Eres un senior mobile developer especialista en apps nativas y multiplataforma con foco en rendimiento, UX y accesibilidad',
    tarea: 'Implementa la funcionalidad mobile descrita. Requisitos: 1) componentes bien estructurados y reutilizables, 2) manejo de estado correcto, 3) accesibilidad (labels, roles, contraste), 4) estados de carga y error visibles para el usuario.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'no uses dependencias externas salvo las indicadas. Código listo para integrar sin modificar la arquitectura existente.',
    outputType: 'código listo para copiar',
    ext: 'respuesta detallada y completa',
    tono: 'técnico y preciso',
    cot: false,
    sc: true,
    xml: false,
    neg: true,
    ej: false,
    pre: true,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'Componente mobile con estado, accesibilidad y manejo de errores',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Qué necesitas implementar', placeholder: 'Pantalla, componente, navegación, integración de API, feature...' },
      { id: 'stack', status: 'required', label: 'Stack mobile', placeholder: 'React Native, Flutter, Swift/SwiftUI, Kotlin, Expo...' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricción' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  // ─── PLANIFICACIÓN ───────────────────────────────────────────────────────────

  sprint: {
    rol: 'Eres un product manager y tech lead con experiencia en desarrollo ágil de software',
    tarea: 'Crea un plan de sprints basado en los requisitos o backlog adjunto. Para cada sprint define: 1) objetivo en una frase, 2) lista de tareas priorizadas por impacto, 3) dependencias críticas, 4) definición de "done". Usa sprints de 2 semanas.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'sé realista con la capacidad del equipo. Mejor under-promise y over-deliver que sobrecargar el sprint.',
    outputType: 'guía paso a paso numerada con acciones concretas',
    ext: 'respuesta detallada y completa',
    tono: 'profesional y directo, sin florituras ni relleno',
    cot: true,
    sc: false,
    xml: true,
    neg: false,
    ej: false,
    pre: false,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'Plan de sprints 2 semanas: objetivo, tareas, dependencias y DoD',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Requisitos o backlog', placeholder: 'Lista de funcionalidades, historias de usuario, objetivos del producto...' },
      { id: 'stack', status: 'required', label: 'Stack del proyecto', placeholder: 'Next.js + Supabase, Django + React, etc.' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricción de capacidad' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  analisis: {
    rol: 'Eres un analista de sistemas y product manager con experiencia en desarrollo de aplicaciones SaaS',
    tarea: 'Analiza los requisitos de la nueva funcionalidad descrita. Entrega: 1) resumen técnico, 2) casos de uso principales (happy path + edge cases), 3) impacto en el sistema actual, 4) estimación de complejidad (baja/media/alta) con justificación, 5) riesgos técnicos identificados.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'si hay ambigüedad en los requisitos, listarla explícitamente en lugar de asumir',
    outputType: 'informe estructurado con secciones y subsecciones numeradas',
    ext: 'respuesta de entre 300 y 500 palabras',
    tono: 'técnico y preciso',
    cot: true,
    sc: false,
    xml: true,
    neg: true,
    ej: false,
    pre: false,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'Casos de uso, impacto, complejidad, riesgos y ambigüedades del cambio',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Descripción de la funcionalidad', placeholder: 'Qué debe hacer, quién lo usará, integración con lo que existe, casos de uso...' },
      { id: 'stack', status: 'required', label: 'Stack', placeholder: 'Next.js + Supabase, Django + PostgreSQL, etc.' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricción de análisis' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  sysprompt: {
    rol: 'Eres un arquitecto de sistemas de IA especialista en diseño de system prompts para agentes de producción',
    tarea: 'Diseña un system prompt robusto para el agente o app descrita. Debe: 1) establecer rol y tono del agente, 2) definir límites claros de comportamiento, 3) dar instrucciones de formato de respuesta, 4) manejar casos fuera de alcance con gracia.',
    proyecto: '',
    stack: 'Claude API, Anthropic',
    destino: '',
    restriccion: 'el agente nunca debe alucinar ni inventar datos — si no sabe algo, debe decirlo explícitamente',
    outputType: 'system prompt listo para copiar, sin explicaciones adicionales',
    ext: 'respuesta detallada y completa',
    tono: 'técnico y preciso',
    cot: false,
    sc: true,
    xml: false,
    neg: true,
    ej: true,
    pre: true,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'System prompt: rol, límites, formato y manejo de casos borde',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Describe el agente o app', placeholder: 'Qué hace, qué usuarios lo usan, tono, límites de comportamiento...' },
      { id: 'proyecto', status: 'required', label: 'Nombre del agente o app', placeholder: 'Asistente de ventas, Auditor de código, Chatbot de soporte...' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricción base' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  // ─── CONTENIDO Y COMUNICACIÓN ────────────────────────────────────────────────

  blog_articulo: {
    rol: 'Eres un escritor experto en contenido largo, divulgación y storytelling para audiencias profesionales',
    tarea: 'Escribe el artículo basado en el tema y notas adjuntas. Estructura: 1) título que genere interés real sin ser clickbait, 2) introducción con un gancho concreto (dato, pregunta o anécdota), 3) desarrollo con ejemplos o evidencia, 4) conclusión con takeaway accionable.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'no uses frases de relleno tipo "En el mundo actual..." ni "Es importante destacar que...". Primera frase con impacto directo.',
    outputType: 'artículo listo para publicar',
    ext: 'blog 600-900 palabras, artículo largo 1.200-2.000 palabras según la profundidad del tema',
    tono: 'profesional y directo, sin florituras ni relleno',
    cot: false,
    sc: false,
    xml: false,
    neg: true,
    ej: false,
    pre: true,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'Artículo con gancho, evidencia y takeaway accionable',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Tema y puntos clave', placeholder: 'De qué trata, ángulo o perspectiva, datos concretos, estructura deseada...' },
      { id: 'destino', status: 'required', label: 'Para quién es', placeholder: 'Desarrolladores, directivos, emprendedores, público general...' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricciones de estilo' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  educacion: {
    rol: 'Eres un pedagogo y experto en el dominio solicitado, especialista en hacer comprensibles conceptos complejos mediante analogías, ejemplos progresivos y estructura clara',
    tarea: 'Explica el concepto o tema descrito. Estructura: 1) explicación en lenguaje adaptado al destinatario, 2) analogía con algo cotidiano, 3) ejemplo concreto y mínimo, 4) los errores más comunes y cómo evitarlos.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'adapta el nivel al destinatario indicado. No simplifiques de más si es técnico, no abrumes si es principiante.',
    outputType: 'explicación clara con secciones diferenciadas',
    ext: 'respuesta concisa, máximo 400 palabras salvo que la complejidad lo requiera',
    tono: 'claro, didáctico y cercano sin perder rigor',
    cot: true,
    sc: false,
    xml: false,
    neg: true,
    ej: true,
    pre: false,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'Explicación con analogía, ejemplo mínimo y errores comunes',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Qué quieres explicar', placeholder: 'Concepto, tecnología, proceso, algoritmo, idea...' },
      { id: 'destino', status: 'required', label: 'Nivel del destinatario', placeholder: 'Principiante sin conocimientos, dev junior, directivo no técnico...' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricción de nivel' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  email: {
    rol: 'Eres un copywriter B2B especialista en emails de captación y seguimiento comercial con alta tasa de apertura y respuesta',
    tarea: 'Redacta el email comercial descrito. Debe tener: 1) asunto que genere curiosidad sin ser clickbait, 2) primera línea que conecte con el dolor del receptor, 3) propuesta de valor en máx. 3 líneas, 4) CTA claro y sin fricción.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'máximo 150 palabras en el cuerpo. Sin emojis. Sin frases de relleno tipo "Espero que este email te encuentre bien."',
    outputType: 'email listo para enviar con asunto y cuerpo separados',
    ext: 'respuesta concisa, máximo 150 palabras, sin relleno',
    tono: 'comercial y persuasivo, orientado al beneficio del receptor',
    cot: false,
    sc: false,
    xml: false,
    neg: true,
    ej: false,
    pre: true,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'Email captación B2B: asunto + propuesta de valor + CTA en 150 palabras',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Contexto del receptor', placeholder: 'Empresa, sector, problema que tiene, por qué le escribes ahora...' },
      { id: 'destino', status: 'required', label: 'Cargo del receptor', placeholder: 'Director general, responsable de IT, jefe de compras...' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricciones de formato' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  linkedin: {
    rol: 'Eres un experto en personal branding y contenido B2B para LinkedIn con foco en generar conversación y visibilidad profesional',
    tarea: 'Escribe un post de LinkedIn basado en el caso o idea descrita. Estructura ganadora: 1) primera línea que pare el scroll (no empieces con "Hoy quiero hablaros de..."), 2) desarrollo con caso real o dato concreto, 3) aprendizaje o reflexión accionable, 4) pregunta o CTA para generar comentarios.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'tono serio y profesional. Sin florituras. Sin frases de gurú tipo "El futuro es ahora." Máximo 1.200 caracteres.',
    outputType: 'post listo para publicar',
    ext: 'respuesta concisa, máximo 1.200 caracteres',
    tono: 'profesional y directo, sin florituras ni relleno',
    cot: false,
    sc: false,
    xml: false,
    neg: true,
    ej: false,
    pre: true,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'Post LinkedIn: gancho, caso real, aprendizaje y CTA',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Caso o idea para el post', placeholder: 'Proyecto reciente, aprendizaje, reflexión, dato concreto que quieras compartir...' },
      { id: 'destino', status: 'required', label: 'Tu audiencia en LinkedIn', placeholder: 'Directivos de PYME, developers, emprendedores, profesionales de marketing...' },
      { id: 'restriccion', status: 'prefilled', label: 'Restricciones de estilo' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  propuesta: {
    rol: 'Eres un consultor de ventas B2B con experiencia en digitalización y transformación de empresas',
    tarea: 'Redacta una propuesta comercial para el cliente descrito. Estructura: 1) diagnóstico del problema del cliente, 2) solución propuesta, 3) beneficios concretos y ROI estimado, 4) inversión y condiciones, 5) próximos pasos.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'tono cercano pero profesional. Sin jerga técnica. El cliente debe sentir que entiendes su negocio antes que el tuyo.',
    outputType: 'propuesta comercial con: problema, solución, beneficios y precio',
    ext: 'respuesta media de entre 300 y 500 palabras',
    tono: 'comercial y persuasivo, orientado al beneficio del cliente',
    cot: false,
    sc: false,
    xml: false,
    neg: true,
    ej: false,
    pre: true,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'Propuesta B2B: diagnóstico, solución, ROI y próximos pasos',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Contexto del cliente', placeholder: 'Sector, tamaño, problema principal, situación actual...' },
      { id: 'destino', status: 'required', label: 'Cargo del decisor', placeholder: 'Director general, responsable de compras, gerente...' },
      { id: 'restriccion', status: 'prefilled', label: 'Tono y estilo' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  doc: {
    rol: 'Eres un redactor técnico experto en documentación de software y propuestas profesionales',
    tarea: 'Genera un documento profesional basado en el material adjunto. Estructura: 1) resumen ejecutivo (máx. 150 palabras), 2) hallazgos detallados con tabla de prioridades, 3) plan de acción con responsables y fechas estimadas.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: '',
    outputType: 'documento estructurado con portada, secciones y conclusión',
    ext: 'respuesta detallada y completa, sin omitir ningún punto relevante',
    tono: 'profesional y directo, sin florituras ni relleno',
    cot: false,
    sc: false,
    xml: true,
    neg: false,
    ej: false,
    pre: false,
    matType: 'documento',
    matFile: '',
    quickSummary: 'Documento: resumen ejecutivo, hallazgos y plan de acción',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Material a documentar', placeholder: 'Pega el material técnico o comercial que quieres convertir en documento...' },
      { id: 'destino', status: 'required', label: 'Para quién es el documento', placeholder: 'Cliente no técnico, equipo técnico, dirección, auditor...' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

  nis2: {
    rol: 'Eres un consultor de ciberseguridad especialista en NIS2, cumplimiento normativo y auditoría de sistemas',
    tarea: 'Genera el documento de cumplimiento NIS2 para la empresa indicada. Incluye: 1) análisis de brecha respecto a los requisitos NIS2, 2) inventario de medidas ya implementadas, 3) tabla de medidas pendientes con prioridad y responsable, 4) política de seguridad adaptada.',
    proyecto: '',
    stack: '',
    destino: '',
    restriccion: 'lenguaje claro, sin jerga jurídica innecesaria. El cliente debe poder implementar las medidas sin un equipo IT dedicado.',
    outputType: 'informe estructurado con secciones y subsecciones numeradas',
    ext: 'respuesta detallada y completa, sin omitir ningún punto relevante',
    tono: 'profesional y directo, sin florituras ni relleno',
    cot: true,
    sc: false,
    xml: true,
    neg: true,
    ej: false,
    pre: false,
    matType: 'contexto',
    matFile: '',
    quickSummary: 'Análisis de brecha NIS2 + medidas pendientes con prioridad',
    visibleFields: [
      { id: 'material', status: 'required', label: 'Información de la empresa', placeholder: 'Sector, tamaño, servicios críticos, sistemas actuales, medidas ya implementadas...' },
      { id: 'proyecto', status: 'required', label: 'Nombre de la empresa', placeholder: 'Empresa SL, Tecnología SA...' },
      { id: 'destino', status: 'prefilled', label: 'Destinatario' },
      { id: 'criterios', status: 'advanced', label: 'Criterios adicionales' },
    ],
  },

};
