import type { ValidationCase } from '@/types/prompt'

export const VALIDATION_CASES: ValidationCase[] = [
  {
    id: 'bug-fix-scope',
    name: 'Fix con scope minimo',
    description: 'Comprueba si el prompt guia al modelo a aislar causa raiz, corregir lo minimo y no tocar codigo sano.',
    templateIds: ['fix', 'app_existente'],
    scenario: [
      'Un componente React guarda un formulario dos veces.',
      'El bug aparece solo al pulsar Enter dentro del input.',
      'El codigo relevante incluye un onSubmit en el form y un onKeyDown en el input.',
      'El resultado deseado es un parche minimo sin reestructurar el componente.',
    ].join('\n'),
    baselinePrompt: 'Arregla este bug en mi componente React.',
    expectedSignals: [
      'Identifica causa raiz antes del parche',
      'Pide o usa el codigo relevante',
      'Limita el cambio al flujo afectado',
      'Incluye criterios para verificar que no hay doble envio',
    ],
    failureSignals: [
      'Reescribe todo el componente sin necesidad',
      'Inventa archivos o dependencias',
      'Ignora el caso Enter',
      'No explica como validar el fix',
    ],
    criteria: [
      {
        id: 'root-cause',
        label: 'Causa raiz',
        description: 'Exige identificar la causa raiz exacta antes de proponer codigo.',
        weight: 20,
        keywords: ['causa raiz', 'causa exacta', 'identifica la causa', 'por que ocurre'],
      },
      {
        id: 'minimal-scope',
        label: 'Scope minimo',
        description: 'Evita reescrituras y cambios fuera del bug.',
        weight: 20,
        keywords: ['scope exacto', 'minima necesaria', 'no cambies nada fuera', 'sin reescribir', 'no toques'],
      },
      {
        id: 'reference-material',
        label: 'Material real',
        description: 'Pide codigo, logs o material antes de asumir implementacion.',
        weight: 15,
        keywords: ['codigo adjunto', 'material', 'archivo', 'si necesitas ver', 'no inventes archivos'],
      },
      {
        id: 'acceptance',
        label: 'Verificacion',
        description: 'Incluye criterios o comprobaciones para saber que el fix funciona.',
        weight: 20,
        keywords: ['criterios', 'verifica', 'validar', 'pruebas', 'edge cases', 'regresiones'],
      },
      {
        id: 'anti-hallucination',
        label: 'No inventar',
        description: 'Bloquea rutas, APIs o dependencias no presentes.',
        weight: 25,
        keywords: ['no inventes', 'suposiciones', 'informacion critica', 'dependencias', 'rutas'],
      },
    ],
  },
  {
    id: 'security-audit',
    name: 'Auditoria con hallazgos verificables',
    description: 'Comprueba si el prompt fuerza severidad, evidencia y acciones concretas en una revision tecnica.',
    templateIds: ['audit', 'nis2'],
    scenario: [
      'Una ruta API recibe datos de usuario y consulta una base de datos.',
      'Hay riesgo de autorizacion incorrecta y validacion insuficiente.',
      'La salida debe separar hallazgos reales, inferencias y recomendaciones.',
    ].join('\n'),
    baselinePrompt: 'Audita este codigo y dime si hay problemas.',
    expectedSignals: [
      'Clasifica por severidad',
      'Relaciona cada hallazgo con evidencia',
      'Distingue hecho, inferencia y suposicion',
      'Propone mitigacion accionable',
    ],
    failureSignals: [
      'Lista vulnerabilidades genericas sin evidencia',
      'No prioriza hallazgos',
      'Inventa tecnologia o endpoints',
      'No diferencia riesgo real de sospecha',
    ],
    criteria: [
      {
        id: 'severity',
        label: 'Severidad',
        description: 'Pide clasificar hallazgos por impacto.',
        weight: 20,
        keywords: ['severidad', 'critica', 'alta', 'media', 'baja', 'prioridad'],
      },
      {
        id: 'evidence',
        label: 'Evidencia',
        description: 'Exige pruebas o referencias al material analizado.',
        weight: 25,
        keywords: ['evidencia', 'respaldada', 'material', 'hechos confirmados', 'codigo adjunto'],
      },
      {
        id: 'uncertainty',
        label: 'Incertidumbre',
        description: 'Separa hechos, inferencias y suposiciones.',
        weight: 20,
        keywords: ['hechos', 'inferencias', 'suposiciones', 'si falta informacion', 'ambiguous'],
      },
      {
        id: 'mitigation',
        label: 'Mitigacion',
        description: 'Pide acciones de remediacion aplicables.',
        weight: 20,
        keywords: ['mitigacion', 'solucion', 'acciones', 'plan de accion', 'corregir'],
      },
      {
        id: 'scope-control',
        label: 'Control de alcance',
        description: 'Evita diagnosticos no respaldados.',
        weight: 15,
        keywords: ['no inventes', 'no hagas suposiciones', 'no rellenes huecos', 'datos no respaldados'],
      },
    ],
  },
  {
    id: 'app-blueprint',
    name: 'Blueprint de app verificable',
    description: 'Comprueba si el prompt define producto, datos, permisos, UX y aceptacion antes de implementar.',
    templateIds: ['conversion', 'analisis', 'sprint', 'app_existente'],
    scenario: [
      'Una app interna necesita usuarios, roles, panel principal, historial y exportacion.',
      'Faltan detalles sobre permisos e integraciones.',
      'El resultado deseado es un plan por fases antes de escribir codigo.',
    ].join('\n'),
    baselinePrompt: 'Crea una app interna con dashboard y usuarios.',
    expectedSignals: [
      'Define pantallas y flujos',
      'Define entidades de datos',
      'Pregunta por permisos e integraciones faltantes',
      'Incluye criterios de aceptacion verificables',
      'Separa fases antes de implementar',
    ],
    failureSignals: [
      'Empieza a implementar sin requisitos',
      'Asume roles o integraciones',
      'No define datos',
      'No incluye criterios de done',
    ],
    criteria: [
      {
        id: 'screens',
        label: 'Pantallas y flujos',
        description: 'Incluye pantallas, rutas o flujos principales.',
        weight: 20,
        keywords: ['pantallas', 'flujos', 'dashboard', 'login', 'vista', 'navegacion'],
      },
      {
        id: 'data',
        label: 'Datos',
        description: 'Define entidades, relaciones o estructura de datos.',
        weight: 20,
        keywords: ['datos', 'entidades', 'relaciones', 'modelo', 'schema', 'base de datos'],
      },
      {
        id: 'permissions',
        label: 'Permisos',
        description: 'Considera roles, permisos y limites de acceso.',
        weight: 15,
        keywords: ['roles', 'permisos', 'autorizacion', 'admin', 'usuario'],
      },
      {
        id: 'phases',
        label: 'Fases',
        description: 'Evita saltar a codigo sin fase de requisitos o plan.',
        weight: 20,
        keywords: ['fase', 'requisitos', 'plan', 'arquitectura', 'no implementes codigo'],
      },
      {
        id: 'acceptance',
        label: 'Aceptacion',
        description: 'Pide criterios verificables para cerrar el trabajo.',
        weight: 25,
        keywords: ['criterios de aceptacion', 'criterios verificables', 'done', 'pruebas necesarias', 'validar'],
      },
    ],
  },
]
